context:
  seafoam: &sf "#f5f8f7"
  midnight: &mn "#004152"
  buoylight: &bl "#cdf8eb"
  poollight: &pl "#c2f7ff"
  sunset: &ss "#ffc8be"
  action: &actn "#00ecc9"
  white: &ff "#ffffff"
  silver: &slvr "#a0aaaf"
  gold: &gld "#b9a879"

variants:
  - name: default
    hidden: true

  - name: Seafoam
    context:
      bgColor: *sf
      textColor: *mn
#      buttonBg:
#      buttonColor:

  - name: Midnight
    context:
      bgColor: *mn
      textColor: *ff
#      buttonBg:
#      buttonColor:

  - name: Buoylight
    context:
      bgColor: *bl
      textColor: *mn
#      buttonBg:
#      buttonColor:

  - name: Poollight
    label: Pool light
    context:
      bgColor: *pl
      textColor: *mn
      buttonBg: *mn
      buttonColor: *ff

  - name: Sunset
    context:
      bgColor: *ss
      textColor: *mn
      buttonBg: *mn
      buttonColor: *ff

  - name: Bronze
    context:
      bgColor: *mn
      textColor: *ff
      buttonBg: *actn
      buttonColor: *mn

  - name: Silver
    context:
      bgColor: *slvr
      textColor: *ff
      buttonBg: *actn
      buttonColor: *mn

  - name: Gold
    context:
      bgColor: *gld
      textColor: *ff
      buttonBg: *actn
      buttonColor: *mn
