label: Tallink
context:
  blockData: '@b2-templ.blockData'

variants:
  - name: default
    hidden: true
  - name: Seafoam
    context:
      theme: '@theme--seafoam-tlnk'
  - name: buoylight
    context:
      theme: '@theme--buoylight-tlnk'
