collated: false

context:
  groupId: 1539080342111
  versions:
    - label: Gold
      index: 1
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD'))"
      phone: +46 (0)20 55 55 50
    - label: Default
      index: 0
      default: true


variants:
  - name: default
    label: CO-dynamic
    notes: Dynamic fragment GOLD/DEFAULT
    context:
      clubone: true

  - name: regular
    context:
      regular: true

  - name: regular silja
    context:
      regular: true
      market: silja

  - name: regular tallink
    context:
      regular: true
      market: tallink

  - name: CO Silja
    context:
      clubone: true
      market: silja

  - name: CO Tallink
    context:
      clubone: true
      market: tallink

  - name: pretrip silja
    context:
      pretrip: true
      market: silja
