preview: "@preview--header"
collated: false
context:
  groupId: 1539080342102
  textColor: "#ffffff"

  imageHref: "https://www.tallinksilja.com/lv/web/lv/club-one"
  buttonHref: "https://www.tallink.lv/lv/club-one?col=1&colr=/et/club-one"
  buttonText: Ienākt
  levelName: Bronze līmenis
  levelPoints: Līmeņa punkti
  levelEnd: 	Līmeņa derīguma termiņš
  bonusPoints: Bonusa punkti
  expThisMonth: Derīgi līdz šī mēneša beigām
  expNxtMonth: Derīgi līdz nākamā mēneša beigām
  manageAccount: Tavs Club One profils un labākie piedāvājumi
  theme: "@theme--bronze"
  logo: co-tallink

  versions:
    - label: B Lp0 Bp1 Exp1
      index: 1
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'BRONZE')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints !== 0) || (context.profile.cusNextMonthsExpPoints !== 0))"

      points: true
      pointsExpire: true
    - label: B LpBp1 Exp0
      index: 2
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'BRONZE')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"

      points: true
    - label: B All 0
      index: 3
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'BRONZE')) && (context.profile.cusLevelPoints === 0) && (context.profile.cusBonusPoints === 0) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"


    - label: S All 1
      index: 4
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'SILVER')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints !== 0) || (context.profile.cusNextMonthsExpPoints !== 0))"
      theme: "@theme--silver"
      levelName: 	Silver līmenis
      points: true
      pointsExpire: true
      levelExpire: true
    - label: S LpBp1 Exp0
      index: 5
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'SILVER')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      theme: "@theme--silver"
      levelName: 	Silver līmenis
      points: true
      levelExpire: true
    - label: S All 0
      index: 6
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'SILVER')) && (context.profile.cusLevelPoints === 0) && (context.profile.cusBonusPoints === 0) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      theme: "@theme--silver"
      levelName: 	Silver līmenis
      levelExpire: true

    - label: G All 1
      index: 7
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints !== 0) || (context.profile.cusNextMonthsExpPoints !== 0))"
      theme: "@theme--gold"
      levelName: Gold līmenis
      points: true
      pointsExpire: true
      levelExpire: true
    - label: G LpBp1 Exp0
      index: 8
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      theme: "@theme--gold"
      levelName: Gold līmenis
      points: true
      levelExpire: true
    - label: G All 0
      index: 9
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD')) && (context.profile.cusLevelPoints === 0) && (context.profile.cusBonusPoints === 0) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      theme: "@theme--gold"
      levelName: Gold līmenis
      levelExpire: true

    - label: Default
      index: 0
      #    expression: ""
      #    }
      default: true
      levelExpire: true
      points: true
      pointsExpire: true

variants:
  - name: default
    context:
      label: Default
      index: 0
      #    expression: ""
      #    }
      default: true
      levelExpire: true
      points: true
      pointsExpire: true
  - name: dynamic
