collated: false
context:
  groupId: 1539080342116
  clubone: true
  versions:
    - label: Gold
      index: 1
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD'))"
      content: Club One Gold-asiakkaat<br>010 80 4132<br>(8,35 snt/puh + 16,69 snt/min)<br>
    - label: Default
      index: 0
      default: true

variants:
  - name: default
    label: CO-dynamic
    notes: Dynamic fragment GOLD/DEFAULT
