collated: false
context:
  groupId: 1539080342924
  clubone: true
  versions:
    - label: Gold
      index: 1
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.targetData.cusTierLevel === 'GOLD'))"
      content: Club One Gold-kunder<br> 010 80 4132<br>(8,35 snt/samtal + 16,69 snt/min)<br>
    - label: Default
      index: 0
      default: true

variants:
  - name: default
    label: CO-dynamic
    notes: Dynamic fragment GOLD/DEFAULT
