label: Silja
context:
  blockData: '@b2-templ.blockData'

variants:
  - name: default
    hidden: true
  - name: mist
    context:
      theme: '@theme--mist-slj'
  - name: mist-cta
    context:
      theme: '@theme--mist-slj'
      cta: true
  - name: Sunset
    context:
      theme: '@theme--sunset-slj'
  - name: midnight
    context:
      theme: '@theme--midnight-slj'
  - name: buoylight
    context:
      theme: '@theme--buoylight-slj'
  - name: seafoam
    hidden: true
    context:
      theme: '@theme--seafoam-slj'
