preview: "@preview--header"
collated: false
context:
  groupId: 1539080343001
  textColor: "#ffffff"

  imageHref: "https://www.tallinksilja.se/club-one"
  buttonHref: "https://www.tallinksilja.se/club-one?col=1&colr=/club-one"
  buttonText: Logga in
  levelName: Bronzenivå
  levelPoints: Nivåpoäng
  levelEnd: Nivå giltig till
  bonusPoints: Bonuspoäng
  expThisMonth: Förfaller denna månad
  expNxtMonth: Förfaller nästa månad
  manageAccount: Se aktuellt poängsaldo och erbjudanden
  theme: "@theme--sunset"
  logo: co-silja

  versions:
    - label: B Lp0 Bp1 Exp1
      index: 1
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'BRONZE')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints !== 0) || (context.profile.cusNextMonthsExpPoints !== 0))"
      points: true
      pointsExpire: true
    - label: B LpBp1 Exp0
      index: 2
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'BRONZE')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      points: true
    - label: B All 0
      index: 3
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'BRONZE')) && (context.profile.cusLevelPoints === 0) && (context.profile.cusBonusPoints === 0) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"


    - label: S All 1
      index: 4
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'SILVER')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints !== 0) || (context.profile.cusNextMonthsExpPoints !== 0))"
      levelName: Silvernivå
      points: true
      pointsExpire: true
      levelExpire: true
    - label: S LpBp1 Exp0
      index: 5
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'SILVER')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      levelName: Silvernivå
      levelExpire: true
      points: true
    - label: S All 0
      index: 6
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'SILVER')) && (context.profile.cusLevelPoints === 0) && (context.profile.cusBonusPoints === 0) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      levelName: Silvernivå
      levelExpire: true

    - label: G All 1
      index: 7
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints !== 0) || (context.profile.cusNextMonthsExpPoints !== 0))"
      levelName: Goldnivå
      points: true
      pointsExpire: true
      levelExpire: true
    - label: G LpBp1 Exp0
      index: 8
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD')) && (/*@nlGroup*/(context.profile.cusLevelPoints !== 0) || (context.profile.cusBonusPoints !== 0)) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      levelName: Goldnivå
      points: true
      levelExpire: true
    - label: G All 0
      index: 9
      expression: "/*@nlGroup*/(/*@nlEnumeration*/(context.profile.cusTierLevel === 'GOLD')) && (context.profile.cusLevelPoints === 0) && (context.profile.cusBonusPoints === 0) && (/*@nlGroup*/(context.profile.cusCurrentMonthsExpPoints === 0) && (context.profile.cusNextMonthsExpPoints === 0))"
      levelName: Goldnivå
      levelExpire: true

    - label: Default
      index: 0
      #    expression: ""
      #    }
      default: true
      levelExpire: true
      points: true
      pointsExpire: true

variants:
  - name: default
    context:
      label: Default
      index: 0
      #    expression: ""
      #    }
      default: true
      levelExpire: true
      points: true
      pointsExpire: true
  - name: dynamic
  - name: version2-dynamic
    context:
       noLogin: true
       groupId: 1539080343005
