
context:
  image: true
variants:
  - name: default
    hidden: true
  - name: Seafoam
    context:
      theme: '@theme--seafoam-tlnk'
  - name: buoylight
    context:
      theme: '@theme--buoylight-tlnk'
