hidden: true
context:
  blockData:
    blockWidth: 267
    blockImage: "https://www.tallink.ee/documents/10192/66843353/344x200_1.png"
    imageWidth: 267
    blockTitle: "Lorem ipsum dolor"
    blockText: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil, quod, voluptas! Adipisci consectetur ipsa nobis quia voluptatem. Accusamus aliquam animi commodi."
    blockButtonText: "Lorem ipsum"
    marginMultiplier: 2
