label: Tallink
context:
  blockData:
    blockWidth: 172
    imageWidth: 172
    blockImage: "https://www.tallink.ee/documents/10192/66843353/344x200_3.png"
    blockTitle: "Lorem ipsum dolor"
    blockText: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab facilis illo molestiae nesciunt."
    blockButtonText: "Lorem ipsum"
    price:
      old: 19,90€
      new: 15,90€

variants:
  - name: default
    hidden: true
  - name: Seafoam
    context:
      theme: '@theme--seafoam'
  - name: midnight
    context:
      theme: '@theme--midnight'
  - name: buoylight
    context:
      theme: '@theme--buoylight'
  - name: poollight
    context:
      theme: '@theme--poollight'
